name: Code Style Check

on:
  push:
  workflow_dispatch:

concurrency:
  group: csc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codestyle:
    permissions:
      contents: read
    name: Run code style check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out source code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - name: Set up PHP
        uses: shivammathur/setup-php@d37cc3048580de06099c81ded417530716a0d7ab # tag=v2
        with:
          php-version: "7.4"
          coverage: none
          tools: automattic/vipwpcs, phpcompatibility/phpcompatibility-wp

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/checkstyle-problem-matcher.json"

      - name: Run style check
        run: phpcs --report=checkstyle
