name: Static Code Analysis

on:
  push:

env:
  PHP_VERSION: "7.3"

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare the source code
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Archive the source
        run: touch plugin.tgz && tar czf plugin.tgz --exclude=./wordpress/ --exclude=./node_modules/ --exclude=.git/ --exclude="*.tgz" ./

      - name: Upload the source
        uses: actions/upload-artifact@v2
        with:
          name: plugin.tgz
          path: plugin.tgz
          retention-days: 1

  psalm:
    runs-on: ubuntu-latest
    name: Psalm
    needs: prepare
    steps:
      - name: Download the source code
        uses: actions/download-artifact@v2
        with:
          name: plugin.tgz

      - name: Extract the source code
        run: tar xzf plugin.tgz && rm -f plugin.tgz

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Run psalm
        run: vendor/bin/psalm

  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    needs: prepare
    steps:
      - name: Download the source code
        uses: actions/download-artifact@v2
        with:
          name: plugin.tgz

      - name: Extract the source code
        run: tar xzf plugin.tgz && rm -f plugin.tgz

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Run phpstan
        run: vendor/bin/phpstan analyze -c phpstan.neon.dist
